---

- name: 'Remove releasever setting to prevent being stuck at a certain OS release'
  ansible.builtin.file:
    path: '/etc/dnf/vars/releasever'
    state: absent
  become: true

- name: 'Install latest epel repo version'
  ansible.builtin.dnf:
    name:
      - 'dnf-utils'
      - 'epel-release'
    state: latest
    update_cache: true
  become: true

- name: 'Install latest snap version'
  ansible.builtin.dnf:
    name: 'snapd'
    state: latest
    update_cache: true
  become: true

- name: 'Start snapd service'
  ansible.builtin.service:
    name: 'snapd'
    enabled: true
    state: started
  become: true

- name: 'Allow snap classic mode by linking the correct file'
  ansible.builtin.file:
    src: '/var/lib/snapd/snap'
    dest: '/snap'
    state: link
  become: true

- name: 'Install latest certbot version'
  community.general.snap:
    name: 'certbot'
    classic: true
    channel: latest
    state: present
  become: true

- name: 'Link certbot to folder in root path'
  ansible.builtin.file:
    src: '/snap/bin/certbot'
    dest: '/usr/bin/certbot'
    state: link
  become: true

- name: 'Allow certificate folder to be read by all users'
  ansible.builtin.file:
    path: '/etc/letsencrypt/live'
    mode: '0755'
    recurse: false
    state: directory
  become: true

- name: 'Allow archive folder to be read by all users'
  ansible.builtin.file:
    path: '/etc/letsencrypt/archive'
    mode: '0755'
    recurse: false
    state: directory
  become: true

...
