---

- name: 'Remove releasever setting to prevent being stuck at a certain OS release'
  ansible.builtin.file:
    path: '/etc/dnf/vars/releasever'
    state: absent
  become: true

- name: 'Install required python version'
  ansible.builtin.dnf:
    name:
      - python3.11 >= 3.11.5
      - augeas-libs >= 1.13.0
    state: present
    update_cache: true
  become: true

- name: 'Remove old certbot packages'
  ansible.builtin.dnf:
    name: certbot
    state: removed
  become: true

- name: 'Create virtual environment'
  ansible.builtin.pip:
    name: pip
    state: latest
    virtualenv: '/opt/certbot/'
    virtualenv_command: 'python3 -m venv'
  become: true

- name: 'Install latest certbot version'
  ansible.builtin.pip:
    name: certbot
    extra_args: 'certbot'
    virtualenv: '/opt/certbot/'
  become: true

- name: 'Link certbot to folder in root path'
  ansible.builtin.file:
    src: '/opt/certbot/bin/certbot'
    dest: '/usr/bin/certbot'
    state: link
  become: true

- name: 'Add renew job to crontab'
  ansible.builtin.cron:
    job: 'certbot renew'
    name: 'CERTBOT_RENEW'
    special_time: daily
    user: 'root'
  become: true

- name: 'Add update job to crontab'
  ansible.builtin.cron:
    job: '/opt/certbot/bin/pip install --upgrade certbot'
    name: 'CERTBOT_UPDATE'
    special_time: monthly
    user: 'root'
  become: true

- name: 'Allow certificate folder to be read by all users'
  ansible.builtin.file:
    path: '/etc/letsencrypt/live'
    mode: '0755'
    recurse: false
    state: directory
  become: true

- name: 'Allow archive folder to be read by all users'
  ansible.builtin.file:
    path: '/etc/letsencrypt/archive'
    mode: '0755'
    recurse: false
    state: directory
  become: true

...
